devrandom/gitian-builder

target-bin/grab-packages.sh, target-bin/upgrade-system.sh
This PR attempts to close #86.
It simply places a dpkg hold on grub-pc in `upgrade-system.sh` to prevent its upgrade. This should be a fairly conservative approach.
Unfortunately, when `grab-packages.sh` tries to download grub-pc via `apt-get install -q --reinstall -y -d grub-pc`, `apt-get` fails due to the hold. It could remove the hold first (and that works today), but there's no guarantee that old packages will remain available in the archive, so the safer approach was to prevent any held packages from being downloaded. On the slight negative side, this changes the manifest.
=> prevent upgrade of grub-pc which can fail in lxc

bin/gsign
This PR is intended to add the option to gsign to use ECDSA for signing instead of invoking gpg. This feature is useful for Armory, which will be using these tools for reproducible builds. Armory is able to verify ECDSA signatures much easier using its Secure Downloader than it is able to use gpg to verify signatures.
This relies on a script in the Armory source tree to handle the actual signing. That script does not exist yet. I opened this pull request just to get feedback at this time concerning how to handle the connection to Armory to do the actual signing. Besides the way this PR currently does things, there were also the ideas brought up of adding an API/plugin interface or a configuration file to gitian-builder to allow arbitrary signing algorithm/program combinations to be added. …
=> Add ECDSA signing to gsign

bin/gbuild
I find this useful for building potentially-untrusted Bitcoin forks without risking polluting the Bitcoin caches.
=> gbuild: Allow disabling fetch of modified caches with `--cache-read-only` option

README.md
I just added the 'Homebrew' commands for those that prefer Homebrew over MacPorts on OSX, as switching between the two once you already use another one can be a pain and cause problems with packages you use them for.
=> Readme.md OSX Homebrew addition

bin/make-base-vm
The build process for [Bitcoin](https://github.com/bitcoin/bitcoin/blob/master/doc/gitian-building.md) was failing with the following error
```
./bin/gbuild:21:in `system!': failed to run on-target setarch x86_64 bash -x < var/build-script > var/build.log 2>&1 (RuntimeError)
from ./bin/gbuild:137:in `build_one_configuration'
from ./bin/gbuild:267:in `block (2 levels) in <main>'
from ./bin/gbuild:262:in `each'
from ./bin/gbuild:262:in `block in <main>'
from ./bin/gbuild:260:in `each'
from ./bin/gbuild:260:in `<main>'
```
Inside the log file `var/build.log` the entries towards the end show
```
/bin/sh: 1: wget: not found
```
=> Missing wget

bin/make-base-vm, target-bin/bootstrap-fixup.in
It seems like a lsb_release program should be available on any distro if
the appropriate package is installed. So it seems better to use
lsb_release instead of /etc/lsb-release, because Debian doesn't appear
to have /etc/lsb-release.
Let me know if you would rather just have me submit this along with all the other changes needed for Debian guest support. I figured that this is not directly related to Debian guest support, so I would file this separate PR, but it is something that isn't an issue if Ubuntu is the only guest supported.
=> Use lsb_release to get codename rather than /etc/lsb-release

README.md, bin/gbuild, bin/make-base-vm, libexec/copy-from-target, libexec/copy-to-target, libexec/on-target, target-bin/bootstrap-fixup.in
Right now this is just KVM support. Selecting LXC and Debian just prints an error message for now. You need to use [my fork of vmbuilder](https://github.com/josephbisch/vmbuilder) for now if you want to use Debian guests.
The package manifest generation doesn't currently work for Debian guests, so that will have to be disabled if you want to test this PR with Debian guests.
One problem I see with this is that it adds a distro field to the descriptor (needed to determine the username), so there will be issues with using old descriptors. Now that I think about it some more, we could just assume Ubuntu if the distro is not specified.
Also, I'm making the assumption that no two distros will have overlapping suite names, because I'm not changing the naming format for the qcow2 files to include …
=> Initial Debian guest support

bin/make-base-vm
Thanks to Georg Koppen for pointing out that the flavour for Debian should be 686-pae instead of i686-pae.
Also if it is Squeeze or earlier, it is just 686 instead of 686-pae.
The second commit is a work around to avoid an issue where an empty KERNEL_PKG (which was the case with Debian) resulted in two commas in a row in addpkg. The apt-get program interprets the lack of a package name between the commas as specifying the package name as being an empty string. That causes an issue for apt in Squeeze or earlier, due to the bug I linked to in the make-base-vm script.
This prepares gitian-builder to work with Squeeze guests. It still doesn't work for me at this point, but it appears to just require fixes to vmbuilder to get Squeeze working.
=> Fix debian i386

README.md, libexec/copy-from-target, libexec/copy-to-target, libexec/on-target
Now, if a user is using something like on-target directly, that user
doesn't need to set the DISTRO or TUSER variables if using Ubuntu guests
(so the scripts function the same as they did before Debian guest
support was added).
=> Set TUSER to ubuntu by default and update README

README.md, bin/make-base-vm, libexec/copy-from-target, libexec/copy-to-target, libexec/on-target
Fixes #106 
From http://www.openssh.com/txt/release-7.0:
```md
Potentially-incompatible Changes
--------------------------------
* Support for ssh-dss, ssh-dss-cert-* host and user keys is disabled
by default at run-time. These may be re-enabled using the
instructions at http://www.openssh.com/legacy.html
=> ssh: Replace deprecated dsa with rsa

etc/lxc.config.in
I need this to get internet access inside the LXC container in a Debian 8.2 VM. This sets the gateway to the host.
See also: https://github.com/bitcoin/bitcoin/pull/7060
=> Set up IPv4 gateway automatically

libexec/copy-from-target, libexec/copy-to-target
Without this, the caches end up in the wrong place (one level of directories gets removed)
=> Bugfix: copy-{to,from}-target: Strip trailing / from sources to avoid triggering special rsync behaviour

bin/gbuild
- apropos to a discussion about merge request #36 : added a flag in the descriptor and command line flag.
- adding sudo: true in the yml file plus adding a command line flag --allow-sudo will allow script user to elevate permissions with no password.
=> Allow build to use sudo without a password, part deux

bin/make-base-vm
Closes #129 
So you can make local copy of /usr/share/debootstrap/ and
e.g. add there missing e.g. "xenial" or other script/template,
without mucking around in system directory managed by
package manager.
=> Allow custom DEBOOTSTRAP_DIR, to give own template (v3)

README.md, bin/make-base-vm, libexec/make-clean-vm
It can be confusing to new users for make-base-vm to create a lucid vm
by default, so switch to trusty, which is also a LTS release, but isn't
EOL yet. Using lucid with gitian-builder is broken anyway, because
lucid has been moved to old-releases.ubuntu.com since it is EOL and
gitian-builder doesn't support old-releases.ubuntu.com.
See #127 for an example of confusion.
=> Switch to xenial for default suite

bin/make-base-vm, target-bin/bootstrap-fixup.in
I tested this using Arch Linux. I had to place the lxc-init program at /usr/sbin/init.lxc. That may just be because I am using Arch and the version of lxc in Arch was expecting the init program there.
=> Add support for Debian guests using LXC

bin/make-base-vm
Original error:
```
I: Base system installed successfully.
cp: cannot stat 'base-jessie-amd64-bootstrap/usr/lib/x86_64-linux-gnu/lxc/lxc-init': No such file or directory
```
Also updates `bin/gbuild` so the hard-coded `ubuntu` username is switched out.
Contemplating making the Vagrantfile Debian-compatible too... but later.
=> Fixes Debian jessie lxc-init path issue

libexec/stop-target
When running Debian Jessie in KVM, using the halt command shuts down
all services but does not stop the qemu process. Using the poweroff
command avoids this problem.
=> stop-target: use poweroff instead of halt

etc/lxc.config.in, target-bin/bootstrap-fixup.in
This fixes #147 and #128.
This is based on the changes from @jonasschnelli in #147, but I realized that the code in the if statement in `target-bin/bootstrap-fixup.in` wasn't being executed when using the Debian 9 host I was using to reproduce the issue. As you can see in the commit message, it is an issue with a change in the method for detecting that a guest is an LXC guest between LXC 1 and LXC 2. So now the adduser command actually executes and was sufficient to get rid of the sudo-related messages for me.
Also pinging @achow101, since @achow101 seemed to experience the same issue in #128.
=> Fix issues with newer versions of LXC

etc/lxc.config.in
This reverts commit c2ff3f9025ab6d5c7bc8bbfbd72f79d40e119401.
That commit broke the use of gitian on debian jessie.
Fixes: #151
=> Revert "Add LXC mount entry for shm"

README.md
Prompted by change of upstream for vmbuilder:
https://bugs.launchpad.net/ubuntu/+source/vm-builder/+bug/1260062/comments/15
Fixes #143, fixes #144. I believe those two issues are the only ones in our issue tracker that are fixed by changing to the new upstream.
=> Update vmbuilder references in README

bin/gbuild
Recent debian and ubuntu are using a system they call multiarch to handle different architectures. Activating multiarch is required to be able to install 32bits packages on 64bits system for instance.
=> Add support for multiarch

bin/gbuild
Recent ubuntu/debian upgraded mingw to use win32 thread by default instead of the mingw port of pthread. This is a problem because std::thread is not implemented for it, and numerous programs do not compile.
being able to update alternative to set the thread model to posix fixes it. This add the support required to be able to do so within the yml descriptor.
=> Add support for update-alternatives

CODEOWNERS, RELEASE_NOTES, Vagrantfile, bin/gbuild, bin/make-base-vm, libexec/start-target
In this PR:
- default VirtualBox launches to headless
- support debian VirtualBox via Vagrant Cloud images
- Debian on LXC should also work, for hosts that support LXC well (Ubuntu 17.10 has a bug in lxc-execute)
- git submodule support - any submodules are cloned and checked out before the build
=> virtualbox improvements

Vagrantfile, bin/make-base-vm
The move was done long ago, so reflect that here as well.
=> Package git-core has been renamed to git

.gitignore, README.md, bin/make-base-vm, libexec/copy-from-target, libexec/copy-to-target, libexec/make-clean-vm, libexec/on-target, libexec/start-target, libexec/stop-target
This PR adds another VM type: docker containers.
Since vmbuilder appears to be borked in recent versions (at least for how we are using it) and people have had issues with lxc in the past (including myself), I have added the option of using docker containers instead of LXC, KVM, or vbox. Setting up and using the docker containers is just as easy and seamless as the setup for lxc and kvm, except it should actually work since the docker people know what they are doing and have made it easy to actually setup and interact with docker containers.
`make-base-vm` now has a `--docker` switch to enable docker containers. Like with lxc, a `USE_DOCKER` environment variable needs to be set for the other scripts to use docker.
I have tested this with a build of Bitcoin Core 0.16.1rc1. The host is …
=> Add the option to use docker containers

bin/gverify
This adds an option `-p` or `--verify-program` to be able to override `gpg` as used by default.
This is useful on Ubuntu 16.04 where `gpg` still is gpg 1.x, and it is desireable to use `gpg2` instead to be able to verify ECDSA signatures and such.
=> Make verification program configurable for gverify

libexec/copy-to-target
docker cp has a bug where it uses the host machine's uid and group
for copied files and directories even though the copied files and
directories should use the container's user's uid and group. To fix
this, we run chown as root on the copied files and directories to
get the correct permissions.
This bug has caused problems for people whose uid:gid is not 1000:1000. This fixes those problems.
=> [docker] Set permissions to container uid and group

etc/lxc.3.config.in, libexec/config-lxc
There are some options that have been renamed in lxc 3.
=> Add compatibility with lxc 3

bin/make-base-vm
Since 1ae746f68f0e4409197365f775defd9ae901a96c, the LXC disk size is still 10241 MiB.
There are reports about related issues while building Bitcoin Core:
- https://github.com/bitcoin/bitcoin/issues/15541#issuecomment-470160960
- https://github.com/bitcoin/bitcoin/issues/15574
Over time, the sizes of both the Bitcoin Core repository and the cache have been increased. Some target architectures have been added.
This PR increases the LXC disk size from 10241 MiB to 12 GiB (originally suggested by @laanwj).
**Note for reviewers:** There is another [suggestion](https://github.com/bitcoin/bitcoin/pull/15549#issuecomment-470330012) from @laanwj:
>  or make the descriptor clean up the intermediate result after each host build.
As every new build is preceded by creating a fresh clean LXC image: …
=> Increase the LXC disk size from 10241 MiB to 12 GiB

target-bin/bootstrap-fixup.in
The configuration files of the removed `rsyslog` package cause needless work here:
https://github.com/devrandom/gitian-builder/blob/ba69d47c4453119dcb7af24638321df817112de6/target-bin/grab-packages.sh#L11
=> Do not leave configuration files of 'rsyslog' package

RELEASE_NOTES, bin/gbuild
This will make it easier to integrate Gitian with other tools that already provide git clone functionality (ie Jenkins) so it not double clones.
=> Do not fetch remote when it already there

RELEASE_NOTES, bin/gbuild
Resolves #217.
This extends #210 to provide an argument to skip fetching from remote so we don't impact existing workflows and still provide a solution for @ultimaweapon's problem.
=> Add argument to skip fetching the latest remote source

bin/gbuild
The current master `bin/gbuild` fails on OSX (Mojave) when formatting the [`author_date`](https://github.com/devrandom/gitian-builder/blob/master/bin/gbuild#L146). 
The following error is displayed:
```
...
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
[-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
bin/gbuild:147:in `block (2 levels) in build_one_configuration': error looking up author date in ... (RuntimeError)
```
```ruby
author_date = `cd inputs/#{dir} && git log --format=@%at -1 | date +"%F %T" -u -f -`.strip
```
The OSX [`date`](https://ss64.com/osx/date.html) does not support the give arguments. 
Instead of working with the `date` command and [incompatibilities](https://unix.stackexchange.com/questions/940/how-can-i-get …
=> Fixes gbuild failure on OSX

libexec/copy-from-target
Some docker-like container management tools have issues setting the right owner with a plain `cp`. See https://github.com/containers/libpod/issues/3218.
Fix that by switching to the same tar command that is also used by lxc.
=> copy-from-target: docker: Use tar to create files with the correct owner

bin/make-base-vm
The setup scripts install apt-cacher-ng but the docker image didn't use it.
=> Use apt-cacher in Docker image

bin/make-base-vm
Allow to specify a disk / image size when creating the base image in
LXC or KVM.
=> Add a disk size option to make-base-vm

bin/gbuild
For most CI's the constant output while running a task is necessary to keep the CI alive.
So whenever a CI is running gitian it should check the CI env to enable direct logs to the CI STDOUT.
=> [CI-RUNNER] Output the build log directly to the STDOUT

bin/gbuild
I think gitian's initial design was that the gitian host arch is equal to the target host arch. This seems overly restrictive in light of cross-compilation. Thus, enable the generic `linux64` arch.
=> gbuild: Allow for generic linux64 host

bin/gbuild, bin/gsign, bin/gverify
Ruby installed with [Ruby Version Manager (RVM)](https://rvm.io/) doesn't sit at `/usr/bin/ruby`.
=> Update `#!/usr/bin/ruby` to `#!/usr/bin/env ruby`

.gitignore
The target-* pattern intent is to ignore the target vm file when using
LXC, but it also matches the `target-bin/` directory which is an
undesired side-effect.
=> Don't ignore the target-bin/ directory

bin/gbuild
This adds a new section to the descriptor YAML to add an entry to the
`sources.list` and install packages from that source.
The primary use case is to allow for installing packages from the
backport repositories. Example use [from Bitcoin
ABC](https://github.com/Bitcoin-ABC/bitcoin-abc/commit/82e154c2796969676ad36e18206321b0dc5091eb):
```
repositories:
- "distribution": "buster-backports"
"source": "deb http://deb.debian.org/debian/ buster-backports main"
packages:
- "cmake"
```
=> Allow for adding repositories to sources list and install packages

bin/gbuild
After running gbuild, the VM is left running. This unnecessarily
consumes system resources if left alone.
I don't see a strong rationale for leaving the VM dangling after
running, especially since gbuild always cleans up the old VM at the start
of each execution (see line 54, where stop-target is called). By default,
the VM should be stopped. A new option has been added to override this
behavior, should it be useful in other configurations.
=> By default, cleanup the target after use

bin/gverify
Reference here:
https://github.com/bitcoin-core/gitian.sigs/issues/1316
Space in name breaking verify script with gitian sigs. Not sure if we want to allow spaces. If we do this fixes it.
=> fix for spaces in names in bitcoin-core gitian.sigs

bin/make-base-vm
If sudo is not installed, --allow-sudo does not work. Not all images have sudo pre-installed, so make sure it is installed during `make-base-vm`.
=> Always install sudo

bin/gbuild
It is useful to have the number of processors and memory available
in the build script
=> Pass num_procs and memory options into the build script

bin/gbuild, libexec/copy-from-target, libexec/copy-to-target, libexec/gconfig, libexec/make-clean-vm, libexec/on-target, libexec/start-target, libexec/stop-target
When you're using `USE_DOCKER`, `USE_LXC` or `USE_VBOX`, if you specify mutliple variables you're going slowly to some undefined behavior.
Also, if you set a variable with the value 0, `USE_LXC = 0`  the software will see it as using LXC because it's checking if the variable is set whatever the value is.
I added some value check when those variables are used, mainly checking if the value is equal 1. This allow users to specify `USE_*` with the value 0 or 1 and to set multiple variables at once with less conflict.
But still some undefined behavior, like what happen if multiple variables are set to 1.
=> Enable use of USE_* variables with values 0 or 1

bin/gbuild
And fix --skip-fetch .
Follow-up of https://github.com/devrandom/gitian-builder/pull/238.
Features:
* able to fetch a commit that is not in a branch or in the history of a tag (main feature of #238)
* by default do not fetch additional data (feature of #238)
* able to fetch additional data (tags or branches) for later use if related option is specified (for #243)
* able to fetch a tag only (addresses https://github.com/devrandom/gitian-builder/pull/238#issuecomment-740068338)
* `git describe --tags` works when `--fetch-tags` is specified (fixes #243)
* always checkout the desired commit/tag/branch even if `--skip-fetch` is specified (fixes a bug)
@devrandom please review. Thanks.
=> Add --fetch-branches and --fetch-tags options

bin/make-base-vm
Changes to the Ubuntu mirror url were reverted for `target-bin/bootstrap-fixup.in` from #274, but not for `bin/make-base-vm` from #273. 
This reverts the latter because that is currently blocking the creation of new base images with debootstrap.
=> Revert ubuntu mirror url changes from #273

bin/gbuild
#238 still was broken... This is needed to fetch the annotated tag itself. Without it, builds have the wrong internal version and don't match the expected hash
=> Bugfix: gbuild: Fetch specific tag if explicitly named
